Num1=int(input("Enter first number"))
Num2=int(input("Enter second number"))
print("Addition is",(Num1+Num2))
print("Subtraction is ",Num1-Num2)
print("Multiplication is", Num1*Num2)
print("Division is", Num1/Num2)
print("Modulus is",Num1%Num2)
print("Exponent is",Num1**Num2)
print("Positive floor division",Num1//Num2)
print("Negative floor division is", -Num1//Num2)