Cartoons=['Dora','Doreamon','Tom','Jeery','Chotabheem','Ben10','Minato','Anime']
print("Actual list is:--------------------------------")
print(Cartoons)
print("Appending of element:---------------------------")
Cartoons.append('oogy and ccokroaches')
print(Cartoons)
print("Inserting of element into list:------------------")
Cartoons.insert(3,'Chotabheem')
print(Cartoons)
print("poping a element:-------------------------------")
Cartoons.pop()
print(Cartoons)
print("pop element of using indexing:---------------------")
Cartoons.pop(5)
print(Cartoons)
print("removing the element:-----------------------------")
Cartoons.remove('Chotabheem')
print(Cartoons)
print("Reversing of element:------------------------------")
Cartoons.reverse()
print(Cartoons)