Emp_Name=input("Enter the name of the empolyee ---------")
Employee_id=int(input("Enter the id of the employee----"))
Employee_Desg=input("Enter the dsignation of the employee----")
Employee_salary=int(input("enter the Salary of employee----"))
Bonus=int(input("Enter the Bonus of employe----"))
print(f"Employee name : {Emp_Name}")
print(f"Employee_id : {Employee_id}")
print(f"Employee_Designation : {Employee_Desg}")
print(f"Employee Salary : {Employee_salary}")
print(f"Bonus : {Bonus}")